# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/INTRANET/lbruchez/myfiles/GeneticsProject/github/Team_4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/INTRANET/lbruchez/myfiles/GeneticsProject/github/Team_4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/INTRANET/lbruchez/myfiles/GeneticsProject/github/Team_4/CMakeFiles /home/INTRANET/lbruchez/myfiles/GeneticsProject/github/Team_4/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/INTRANET/lbruchez/myfiles/GeneticsProject/github/Team_4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Genetics

# Build rule for target.
Genetics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Genetics
.PHONY : Genetics

# fast build rule for target.
Genetics/fast:
	$(MAKE) -f CMakeFiles/Genetics.dir/build.make CMakeFiles/Genetics.dir/build
.PHONY : Genetics/fast

#=============================================================================
# Target rules for targets named Genetics_UnitTest

# Build rule for target.
Genetics_UnitTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Genetics_UnitTest
.PHONY : Genetics_UnitTest

# fast build rule for target.
Genetics_UnitTest/fast:
	$(MAKE) -f CMakeFiles/Genetics_UnitTest.dir/build.make CMakeFiles/Genetics_UnitTest.dir/build
.PHONY : Genetics_UnitTest/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f CMakeFiles/doc.dir/build.make CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named program_using_tclap

# Build rule for target.
program_using_tclap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 program_using_tclap
.PHONY : program_using_tclap

# fast build rule for target.
program_using_tclap/fast:
	$(MAKE) -f CMakeFiles/program_using_tclap.dir/build.make CMakeFiles/program_using_tclap.dir/build
.PHONY : program_using_tclap/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f test/gtest/CMakeFiles/gtest.dir/build.make test/gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f test/gtest/CMakeFiles/gtest_main.dir/build.make test/gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/Allele.o: src/Allele.cpp.o
.PHONY : src/Allele.o

# target to build an object file
src/Allele.cpp.o:
	$(MAKE) -f CMakeFiles/Genetics.dir/build.make CMakeFiles/Genetics.dir/src/Allele.cpp.o
.PHONY : src/Allele.cpp.o

src/Allele.i: src/Allele.cpp.i
.PHONY : src/Allele.i

# target to preprocess a source file
src/Allele.cpp.i:
	$(MAKE) -f CMakeFiles/Genetics.dir/build.make CMakeFiles/Genetics.dir/src/Allele.cpp.i
.PHONY : src/Allele.cpp.i

src/Allele.s: src/Allele.cpp.s
.PHONY : src/Allele.s

# target to generate assembly for a file
src/Allele.cpp.s:
	$(MAKE) -f CMakeFiles/Genetics.dir/build.make CMakeFiles/Genetics.dir/src/Allele.cpp.s
.PHONY : src/Allele.cpp.s

src/Random.o: src/Random.cpp.o
.PHONY : src/Random.o

# target to build an object file
src/Random.cpp.o:
	$(MAKE) -f CMakeFiles/Genetics.dir/build.make CMakeFiles/Genetics.dir/src/Random.cpp.o
.PHONY : src/Random.cpp.o

src/Random.i: src/Random.cpp.i
.PHONY : src/Random.i

# target to preprocess a source file
src/Random.cpp.i:
	$(MAKE) -f CMakeFiles/Genetics.dir/build.make CMakeFiles/Genetics.dir/src/Random.cpp.i
.PHONY : src/Random.cpp.i

src/Random.s: src/Random.cpp.s
.PHONY : src/Random.s

# target to generate assembly for a file
src/Random.cpp.s:
	$(MAKE) -f CMakeFiles/Genetics.dir/build.make CMakeFiles/Genetics.dir/src/Random.cpp.s
.PHONY : src/Random.cpp.s

src/Simulation.o: src/Simulation.cpp.o
.PHONY : src/Simulation.o

# target to build an object file
src/Simulation.cpp.o:
	$(MAKE) -f CMakeFiles/Genetics.dir/build.make CMakeFiles/Genetics.dir/src/Simulation.cpp.o
.PHONY : src/Simulation.cpp.o

src/Simulation.i: src/Simulation.cpp.i
.PHONY : src/Simulation.i

# target to preprocess a source file
src/Simulation.cpp.i:
	$(MAKE) -f CMakeFiles/Genetics.dir/build.make CMakeFiles/Genetics.dir/src/Simulation.cpp.i
.PHONY : src/Simulation.cpp.i

src/Simulation.s: src/Simulation.cpp.s
.PHONY : src/Simulation.s

# target to generate assembly for a file
src/Simulation.cpp.s:
	$(MAKE) -f CMakeFiles/Genetics.dir/build.make CMakeFiles/Genetics.dir/src/Simulation.cpp.s
.PHONY : src/Simulation.cpp.s

src/SimulationsExecutor.o: src/SimulationsExecutor.cpp.o
.PHONY : src/SimulationsExecutor.o

# target to build an object file
src/SimulationsExecutor.cpp.o:
	$(MAKE) -f CMakeFiles/Genetics.dir/build.make CMakeFiles/Genetics.dir/src/SimulationsExecutor.cpp.o
.PHONY : src/SimulationsExecutor.cpp.o

src/SimulationsExecutor.i: src/SimulationsExecutor.cpp.i
.PHONY : src/SimulationsExecutor.i

# target to preprocess a source file
src/SimulationsExecutor.cpp.i:
	$(MAKE) -f CMakeFiles/Genetics.dir/build.make CMakeFiles/Genetics.dir/src/SimulationsExecutor.cpp.i
.PHONY : src/SimulationsExecutor.cpp.i

src/SimulationsExecutor.s: src/SimulationsExecutor.cpp.s
.PHONY : src/SimulationsExecutor.s

# target to generate assembly for a file
src/SimulationsExecutor.cpp.s:
	$(MAKE) -f CMakeFiles/Genetics.dir/build.make CMakeFiles/Genetics.dir/src/SimulationsExecutor.cpp.s
.PHONY : src/SimulationsExecutor.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Genetics.dir/build.make CMakeFiles/Genetics.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Genetics.dir/build.make CMakeFiles/Genetics.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Genetics.dir/build.make CMakeFiles/Genetics.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/random.o: src/random.cpp.o
.PHONY : src/random.o

# target to build an object file
src/random.cpp.o:
	$(MAKE) -f CMakeFiles/Genetics_UnitTest.dir/build.make CMakeFiles/Genetics_UnitTest.dir/src/random.cpp.o
	$(MAKE) -f CMakeFiles/program_using_tclap.dir/build.make CMakeFiles/program_using_tclap.dir/src/random.cpp.o
.PHONY : src/random.cpp.o

src/random.i: src/random.cpp.i
.PHONY : src/random.i

# target to preprocess a source file
src/random.cpp.i:
	$(MAKE) -f CMakeFiles/Genetics_UnitTest.dir/build.make CMakeFiles/Genetics_UnitTest.dir/src/random.cpp.i
	$(MAKE) -f CMakeFiles/program_using_tclap.dir/build.make CMakeFiles/program_using_tclap.dir/src/random.cpp.i
.PHONY : src/random.cpp.i

src/random.s: src/random.cpp.s
.PHONY : src/random.s

# target to generate assembly for a file
src/random.cpp.s:
	$(MAKE) -f CMakeFiles/Genetics_UnitTest.dir/build.make CMakeFiles/Genetics_UnitTest.dir/src/random.cpp.s
	$(MAKE) -f CMakeFiles/program_using_tclap.dir/build.make CMakeFiles/program_using_tclap.dir/src/random.cpp.s
.PHONY : src/random.cpp.s

src/random_main.o: src/random_main.cpp.o
.PHONY : src/random_main.o

# target to build an object file
src/random_main.cpp.o:
	$(MAKE) -f CMakeFiles/program_using_tclap.dir/build.make CMakeFiles/program_using_tclap.dir/src/random_main.cpp.o
.PHONY : src/random_main.cpp.o

src/random_main.i: src/random_main.cpp.i
.PHONY : src/random_main.i

# target to preprocess a source file
src/random_main.cpp.i:
	$(MAKE) -f CMakeFiles/program_using_tclap.dir/build.make CMakeFiles/program_using_tclap.dir/src/random_main.cpp.i
.PHONY : src/random_main.cpp.i

src/random_main.s: src/random_main.cpp.s
.PHONY : src/random_main.s

# target to generate assembly for a file
src/random_main.cpp.s:
	$(MAKE) -f CMakeFiles/program_using_tclap.dir/build.make CMakeFiles/program_using_tclap.dir/src/random_main.cpp.s
.PHONY : src/random_main.cpp.s

src/test_main.o: src/test_main.cpp.o
.PHONY : src/test_main.o

# target to build an object file
src/test_main.cpp.o:
	$(MAKE) -f CMakeFiles/Genetics_UnitTest.dir/build.make CMakeFiles/Genetics_UnitTest.dir/src/test_main.cpp.o
.PHONY : src/test_main.cpp.o

src/test_main.i: src/test_main.cpp.i
.PHONY : src/test_main.i

# target to preprocess a source file
src/test_main.cpp.i:
	$(MAKE) -f CMakeFiles/Genetics_UnitTest.dir/build.make CMakeFiles/Genetics_UnitTest.dir/src/test_main.cpp.i
.PHONY : src/test_main.cpp.i

src/test_main.s: src/test_main.cpp.s
.PHONY : src/test_main.s

# target to generate assembly for a file
src/test_main.cpp.s:
	$(MAKE) -f CMakeFiles/Genetics_UnitTest.dir/build.make CMakeFiles/Genetics_UnitTest.dir/src/test_main.cpp.s
.PHONY : src/test_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Genetics"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... doc"
	@echo "... test"
	@echo "... program_using_tclap"
	@echo "... Genetics_UnitTest"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... src/Allele.o"
	@echo "... src/Allele.i"
	@echo "... src/Allele.s"
	@echo "... src/Random.o"
	@echo "... src/Random.i"
	@echo "... src/Random.s"
	@echo "... src/Simulation.o"
	@echo "... src/Simulation.i"
	@echo "... src/Simulation.s"
	@echo "... src/SimulationsExecutor.o"
	@echo "... src/SimulationsExecutor.i"
	@echo "... src/SimulationsExecutor.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/random.o"
	@echo "... src/random.i"
	@echo "... src/random.s"
	@echo "... src/random_main.o"
	@echo "... src/random_main.i"
	@echo "... src/random_main.s"
	@echo "... src/test_main.o"
	@echo "... src/test_main.i"
	@echo "... src/test_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

