#ifndef GLOBALS_H
#define GLOBALS_H

#define _MIN_OUTPUT_PRECISION_ 2

#define _PARAM_MUTATIONS_ 1
#define _PARAM_MIGRATION_ 2
#define _PARAM_SELECTION_ 4
#define _PARAM_BOTTLENECK_ 8

#define _DEFAULT_MUTATION_RATE_ 1E-6
#define _MUTATION_MODEL_SIMPLE_ 1
#define _MUTATION_MODEL_MEDIUM_ 2
#define _MUTATION_MODEL_COMPLEX_ 3

#endif
