#ifndef GLOBALS_H
#define GLOBALS_H

#define _MIN_OUTPUT_PRECISION_ 2

#define _INPUT_KEY_GENERATIONS_ "GEN"
#define _INPUT_KEY_REPLICAS_ "REP"
#define _INPUT_KEY_MARKER_SITES_ "SITES"
#define _INPUT_KEY_MODE_ "MODE"
#define _INPUT_KEY_MUTATION_RATES_ "MUT"
#define _INPUT_KEY_MUTATION_KIMURA_ "MUT_KIMURA"
#define _INPUT_KEY_MUTATION_FELSENSTEIN_ "MUT_FELSENSTEIN"


#define _PARAM_NONE_ 0
#define _PARAM_MUTATIONS_ 1
#define _PARAM_MIGRATION_ 2
#define _PARAM_SELECTION_ 4
#define _PARAM_BOTTLENECK_ 8

#define _DEFAULT_MUTATION_RATE_ 1E-6
#define _MUTATION_MODEL_NONE_ 0
#define _MUTATION_MODEL_CANTOR_ 1
#define _MUTATION_MODEL_KIMURA_ 2
#define _MUTATION_MODEL_FELSENSTEIN_ 3

#endif
